compile:
	gcc *.c -o les-with-descritors
	mv ./les-with-descritors ./bin
run:
	./bin/les-with-descritors
compile-test:
	gcc tests/test-main.c les-descritor.c -o les-with-descritors-test
	mv ./les-with-descritors-test ./bin
run-test:
	./bin/les-with-descritors-test
